name: Docker Image CD

on:
  push:
    branches: [ "master" ]
  
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out the codebase
      uses: actions/checkout@v3
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with: 
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    
    - name: Login to ECR
      run: aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/w2g6o0h1

    - name: Build, tag, and push the Docker image
      run: |
        docker build . -t pjehn/continuous_php_image
        docker tag pjehn/continuous_php_image:latest public.ecr.aws/w2g6o0h1/pjehn/continuous_php_image:latest
        docker push public.ecr.aws/w2g6o0h1/pjehn/continuous_php_image:latest